
arenas = ['Joel and Diane Bloom Wellness and Events Center',
       'Worthen Arena', 'Thompson-Boling Arena', 'JMA Wireless Dome',
       'Petersen Events Center', 'John Paul Jones Arena',
       'Lawrence Joel Coliseum', 'Harry A. Gampel Pavilion',
       'McCamish Pavilion', 'KFC Yum! Center',
       'Donald L. Tucker Civic Center', 'Cameron Indoor Stadium',
       'Greensboro Coliseum', 'MVP Arena',
       'The Sandy and John Black Pavilion at Ole Miss',
       'Donald L. Tucker Center', 'Atlantic Union Bank Center',
       'Haas Pavilion', 'Maples Pavilion', 'Moody Coliseum',
       'Enterprise Center', 'Welsh-Ryan Arena',
       'Gateway Christian Academy', 'Kirby Sports Center',
       'Cassell Coliseum', 'Watsco Center', 'Carmichael Arena',
       'Littlejohn Coliseum', 'Reynolds Coliseum',
       'Bon Secours Wellness Arena']

cities = {
    'Joel and Diane Bloom Wellness and Events Center': 'Newark, NJ',
    'Worthen Arena': 'Muncie, IN',
    'Thompson-Boling Arena': "Knoxville, TN",
    'JMA Wireless Dome': 'Syracuse, NY',
    'Petersen Events Center': 'Pittsburgh, PA',
    'John Paul Jones Arena': 'Charlottesville, VA',
    'Lawrence Joel Coliseum': 'Winston-Salem, NC',
    'Harry A. Gampel Pavilion': 'Mansfield, CT',
    'McCamish Pavilion': 'Atlanta, GA',
    'KFC Yum! Center': 'Louisville, KY',
    'Donald L. Tucker Civic Center': 'Tallahassee, FL',
    'Cameron Indoor Stadium': 'Durham, NC',
    'Greensboro Coliseum': 'Greensboro, NC',
    'MVP Arena': 'Albany, NY',
    'The Sandy and John Black Pavilion at Ole Miss': 'University, MS',
    'Atlantic Union Bank Center': 'Harrisonburg, VA',
    'Haas Pavilion': 'Berkley, CA',
    'Maples Pavilion': 'Stanford, CA',
    'Moody Coliseum': 'Dallas, TX',
    'Enterprise Center': 'St. Louis, MO',
    'Welsh-Ryan Arena': 'Evanston, IL',
    'Kirby Sports Center': 'Easton, PA',
    'Cassell Coliseum': 'Blacksburg, VA',
    'Watsco Center': 'Coral Gaples, FL',
    'Carmichael Arena': 'Chapel Hill, NC',
    'Littlejohn Coliseum': 'Clemson, SC',
    'Reynolds Coliseum': 'Raleigh, NC',
    'Bon Secours Wellness Arena': 'Greenville, SC'
    }